---
- name: Install Calico from manifests
  command: |
    kubectl apply -f https://docs.projectcalico.org/v{{ kubernetes_calico_version }}/manifests/calico.yaml {{ "--dry-run=server" if ansible_check_mode }}
  changed_when: "'created' in kubernetes__r_calico.stdout"
  check_mode: no
  register: kubernetes__r_calico

- debug: msg='{{ kubernetes__r_calico.stdout_lines + kubernetes__r_calico.stderr_lines }}'

- name: Wait for Calico readiness
  command: kubectl wait -n kube-system --for=condition=Ready pod -l {{ item }}
  changed_when: no
  register: kubernetes__r_wait
  until: "'condition met' in kubernetes__r_wait.stdout"
  loop:
    - k8s-app=calico-kube-controllers
    - k8s-app=calico-node
