---
# Note: `creates` ensures scripts are re-generated if tool is reinstalled
- name: Generate completion scripts
  shell: '{{ item }} completion bash > ~/.kube/{{ item }}_completion.bash.inc'
  args:
    creates: '~/.kube/{{ item }}_completion.bash.inc{{ "" if not kubernetes__r_install.changed else ".force" }}'
  loop:
    - kubectl
    - kubeadm

- name: Generate crictl completion scripts
  shell: 'crictl completion bash > ~/.kube/crictl_completion.bash.inc'
  args:
    creates: '~/.kube/crictl_completion.bash.inc{{ "" if not kubernetes__r_crictl_install.changed else ".force" }}'
  environment:
    PATH: '/usr/local/bin:{{ ansible_env.PATH }}'

- name: Source completion scripts from bash_profile
  lineinfile:
    path: ~/.bash_profile
    regexp: '{{ item }}_completion.bash.inc'
    line: 'source ~/.kube/{{ item }}_completion.bash.inc'
  loop:
    - kubectl
    - kubeadm
    - crictl
