---
- name: create directory for completion scripts
  file:
    path: ~/.kube
    state: directory
    mode: '0750'

# Note: `creates` ensures scripts are re-generated if kubernetes is reinstalled
- name: generate completion scripts
  shell:
    cmd: '{{ item }} completion bash > ~/.kube/{{ item }}_completion.bash.inc'
    creates: '~/.kube/{{ item }}_completion.bash.inc{{ "" if not kubernetes__r_install.changed else ".force" }}'
  loop:
    - kubectl
    - kubeadm

- name: source completion scripts from bash_profile
  lineinfile:
    path: ~/.bash_profile
    regexp: '{{ item }}_completion.bash.inc'
    line: 'source ~/.kube/{{ item }}_completion.bash.inc'
  loop:
    - kubectl
    - kubeadm
