---
- name: kubeadm join pre-check
  command: >
    kubeadm join phase preflight --config /etc/kubernetes/kubeadm.yaml --ignore-preflight-errors=NumCPU,DirAvailable--etc-kubernetes-manifests,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml
  check_mode: no
  changed_when: no
  register: kubernetes__r_precheck

- debug: msg='{{ kubernetes__r_precheck.stdout_lines + kubernetes__r_precheck.stderr_lines }}'

- block:
  - name: Configure control plane (managers only)
    command: >
      kubeadm join phase control-plane-prepare all --config /etc/kubernetes/kubeadm.yaml
    args:
      creates: /etc/kubernetes/manifests/kube-controller-manager.yaml
    register: kubernetes__r_control_plane

  - debug: msg='{{ kubernetes__r_control_plane.stdout_lines + kubernetes__r_control_plane.stderr_lines }}'
    when: kubernetes__r_control_plane.changed

  - name: Expose control manager and scheduler metrics to prometheus (managers only)
    replace:
      path: '/etc/kubernetes/manifests/kube-{{ item }}.yaml'
      regexp: '127\.0\.0\.1'
      replace: '{{ kubernetes_address }}'
    loop:
      - controller-manager
      - scheduler

  when: kubernetes_role == 'manager'

- name: Join cluster
  command: >
    kubeadm join --config /etc/kubernetes/kubeadm.yaml --skip-phases=preflight,control-plane-prepare
  register: kubernetes__r_join

- debug: msg='{{ kubernetes__r_join.stdout_lines + kubernetes__r_join.stderr_lines }}'
