---
- name: Configure kubeadm
  template:
    dest: /etc/kubernetes/kubeadm.yaml
    src: kubeadm-init.yaml.j2
    mode: 0600
    owner: root
    group: root

- name: Kubeadm init pre-check
  command: >-
    kubeadm init phase preflight --config /etc/kubernetes/kubeadm.yaml
    --ignore-preflight-errors={{ kubernetes_kubeadm_init_ignore_errors | join(",") }}
  check_mode: false
  changed_when: false
  register: kubernetes__r_precheck
  when: kubernetes_precheck

- name: Print result from running kubeadm pre-check
  debug: msg='{{ kubernetes__r_precheck.stdout_lines + kubernetes__r_precheck.stderr_lines }}'
  when: kubernetes_precheck

- name: Configure control plane
  command: kubeadm init phase control-plane all --config /etc/kubernetes/kubeadm.yaml
  args:
    creates: /etc/kubernetes/manifests/kube-controller-manager.yaml
  register: kubernetes__r_control_plane

- name: Print result from configuring control plane  # noqa no-handler
  debug: msg='{{ kubernetes__r_control_plane.stdout_lines + kubernetes__r_control_plane.stderr_lines }}'
  when: kubernetes__r_control_plane.changed

- name: Expose control manager and scheduler metrics to prometheus
  replace:
    path: '/etc/kubernetes/manifests/kube-{{ item }}.yaml'
    regexp: '127\.0\.0\.1'
    replace: '{{ kubernetes_address }}'
  loop:
    - controller-manager
    - scheduler

- name: Initialize cluster          # noqa 301
  command: kubeadm init --config /etc/kubernetes/kubeadm.yaml --upload-certs --skip-phases=preflight,control-plane
  register: kubernetes__r_init

- name: Print result from initializing cluster
  debug: msg='{{ kubernetes__r_init.stdout_lines + kubernetes__r_init.stderr_lines }}'
