---
- name: Create directory for kubernetes config
  file:
    path: /etc/kubernetes
    state: directory
    mode: 0750

- name: Link kubeconfig in root's home
  file:
    dest: ~/.kube/config
    src: /etc/kubernetes/admin.conf
    state: link
    mode: 0400
    force: true
  when: kubernetes_role == 'manager'

- name: Check if node has already joined the cluster
  command: kubectl get nodes -o custom-columns=NAME:.metadata.name --no-headers
  delegate_to: '{{ kubernetes_leader }}'
  check_mode: false
  changed_when: inventory_hostname not in kubernetes__r_joined.stdout_lines
  failed_when:
    - kubernetes__r_joined.rc > 0
    - not (kubernetes_task == 'init' and '"The connection to the server localhost:8080 was refused" not in kubernetes__r_joined.stderr')
  register: kubernetes__r_joined

- name: Initialize cluster with first node
  include_tasks: kubeadm-init.yml
  when:
    - kubernetes_task == 'init'
    - kubernetes__r_joined.changed

- name: Prevent NetworkManager from interfering with Calico
  copy:
    dest: /etc/NetworkManager/conf.d/calico.conf
    content: |
      [keyfile]
      unmanaged-devices=interface-name:cali*;interface-name:tunl*;interface-name:vxlan.calico
    owner: root
    group: root
    mode: 0644

- name: Initialize CNI
  include_tasks: calico.yml
  when:
    - kubernetes_task == 'init'

- name: Join other nodes to cluster
  include_tasks: kubeadm-join.yml
  when:
    - kubernetes_task == 'join'
    - kubernetes__r_joined.changed

- name: Find calico version
  command: >-
    kubectl -n calico-system get deployments.apps calico-kube-controllers
    -o jsonpath='{.spec.template.spec.containers[?(@.name=="calico-kube-controllers")].image}'
  changed_when: false
  register: kubernetes__r_calico_image
  when: kubernetes_role == 'manager'

- name: Install calicoctl
  get_url:
    url: https://github.com/projectcalico/calico/releases/download/{{ kubernetes__r_calico_image.stdout.split(":") | last }}/calicoctl-linux-amd64
    dest: /usr/bin/calicoctl
    owner: root
    group: root
    mode: 0750
    force: true
  when: kubernetes_role == 'manager'

- name: Add labels to nodes
  command: kubectl label --overwrite node {{ inventory_hostname }} {{ kubernetes_node_labels | join(" ") }}
  delegate_to: '{{ kubernetes_leader }}'
  when: kubernetes_node_labels != []
