---
- name: Link kubeconfig in root's home
  file:
    dest: ~/.kube/config
    src: /etc/kubernetes/admin.conf
    state: link
    mode: '0400'
    force: true
  when: kubernetes_role == 'manager'

- name: Configure kubeadm
  template:
    dest: /etc/kubernetes/kubeadm.yaml
    src: 'kubeadm-{{ kubernetes_task }}.yaml.j2'
    mode: '0600'
    owner: root
    group: root

- name: Check if control-plane is already initialized
  stat: path=/etc/kubernetes/admin.conf
  register: kubernetes__r_initialized
  when: kubernetes_role == 'manager'

- name: Setup load balancer
  include_tasks: load-balancer.yml
  when: kubernetes_role == 'manager'

- name: Initialize cluster
  include_tasks: kubeadm-init.yml
  when:
    - kubernetes_role == 'manager'
    - kubernetes_task == 'init'
    - not kubernetes__r_initialized.stat.exists

- name: Bootstrap discovery
  include_tasks: discovery.yml
  when: kubernetes_task == 'init'

- name: Join nodes to cluster
  include_tasks: kubeadm-join.yml
  when: kubernetes_task == 'join'
