---
- name: Configure kubeadm
  template:
    dest: /etc/kubernetes/kubeadm.yaml
    src: kubeadm.yaml.j2
    mode: '0600'
    owner: root
    group: root

- name: Check if control-plane is already initialized
  stat: path=/etc/kubernetes/admin.conf
  register: kubernetes__r_initialized

- include_tasks: kubeadm-init.yml
  when: not kubernetes__r_initialized.stat.exists

- include_tasks: calico.yml
