---
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic
- name: Let iptables see bridged traffic
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    sysctl_file: /etc/sysctl.d/50-kubernetes.conf

- name: Add kubernetes repository
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    exclude: kubelet kubeadm kubectl

- name: Install kubernetes tools {{ kubernetes_version }}
  yum:
    name: '{{ kubernetes_packages }}'
    disable_excludes: kubernetes
    state: '{{ kubernetes_packages_state }}'
    allow_downgrade: yes
  register: kubernetes__r_install

- name: Find kubernetes installed version
  command: kubeadm version -o short
  register: kubernetes__r_installed_version
  check_mode: no
  changed_when: no

- name: Specify node IP for kubelet in multi-interface hosts
  template:
    dest: /etc/sysconfig/kubelet
    src: kubelet.j2
    owner: root
    group: root
    mode: '0644'

- name: Enable kubelet service
  systemd:
    name: kubelet
    state: started
    enabled: true

- name: Bootstrap kubernetes with kubeadm
  import_tasks: kubeadm.yml

- name: Install completion scripts
  import_tasks: completion.yml
