---
# https://kubernetes.io/docs/setup/production-environment/container-runtimes/
- name: fix iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'

- name: add kubernetes repository
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    exclude: kube*

- name: install kubernetes tools
  yum:
    name:
      - 'kubelet-{{ kubernetes_version }}*'
      - 'kubeadm-{{ kubernetes_version }}*'
      - 'kubectl-{{ kubernetes_version }}*'
    disable_excludes: kubernetes

- name: enable kubelet service
  systemd:
    name: kubelet
    enabled: true
